
    		package jpaperf.pay.entity
        
    		
    		
    		import scala.reflect.BeanProperty
        
    		import javax.persistence._
        
        
    		
    		import java.sql.Timestamp
        
    		import jpaperf.pay.entity.PayAccount
        
        
    		
    		/**
    		 * Generated by Siddharta
    		 */
            @Entity
    		class PayAccountItem    {
    			
    			
        
    			
    		
              @BeanProperty
    		  @Id
              var id: Long = _
          
        
    		
              @BeanProperty
    		  @Column
              var amount: String = _
          
              @BeanProperty
    		  @Column
              var transactionType: Long = _
          
              @BeanProperty
    		  @Column
              var inserted: Timestamp = _
          
        
    		
              @BeanProperty
    		  @ManyToOne	
        	  @JoinColumn(name = "account_id")	
              var accountId: PayAccount = _
          
        
    		
        
    		
        
    		
    			
    		
    			
    		}
        