package jpaperf.old

/**
 * Created by pedrofurla on 01/05/14.
 *
 * Based on code created by Zlatko Josic and shared in the Slick mailing list
 * https://groups.google.com/forum/#!msg/scalaquery/zfUL-zyHtAI/2N33yOh939cJ
 */
object EntitiesOld {

  import javax.persistence._
  import scala.beans.BeanProperty
  import java.util.{ArrayList, List}
  import java.sql.Timestamp

  /**
   * Generated by Siddharta
   */
  @Entity()
  @Table(name = "MAIN_TC_USER")
  class MainUser {
    @BeanProperty
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = _

    @BeanProperty
    @Column
    var name: String = _

    @BeanProperty
    @Column
    var surname: String = _

    @BeanProperty
    @Column
    var username: String = _

    @BeanProperty
    @Column
    var password: String = _

    @BeanProperty
    @OneToMany(cascade = Array(CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE), fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    var payAccountList: List[PayAccount] = new ArrayList[PayAccount]
  }

  /**
   * Generated by Siddharta
   */
  @Entity
  @Table(name = "PAY_TD_ACCOUNT")
  class PayAccount {

    @BeanProperty
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = _

    @BeanProperty
    @Column
    var amount: Double = _

    @BeanProperty
    @Column
    var reserved: Double = _

    @BeanProperty
    @ManyToOne
    @JoinColumn(name = "user_id")
    var userId: MainUser = _

    @BeanProperty
    @OneToMany(cascade = Array(CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE), fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id")
    var payAccountItemList: List[PayAccountItem] = new ArrayList[PayAccountItem]
  }

  /**
   * Generated by Siddharta
   */
  @Entity
  class PayAccountItem {

    @BeanProperty
    @Id
    var id: Long = _

    @BeanProperty
    @Column
    var amount: String = _

    @BeanProperty
    @Column
    var transactionType: Long = _

    @BeanProperty
    @Column
    var inserted: Timestamp = _

    @BeanProperty
    @ManyToOne
    @JoinColumn(name = "account_id")
    var accountId: PayAccount = _
  }

}
